project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "assignment_gret1.qmd"
    - "assignment_r.qmd"
website:
  title: "OEKA201AssignmentMAT"
  navbar:
    left:
      - text: "Index"
        href: index.qmd
      - text: "Exercises using Gret1"
        href: assignment_gret1.qmd
      - text: "Exercises using R"
        href: assignment_r.qmd
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    mainfont: "Monospace"
    css: styles.css
  docx:
    toc: true
    toc-depth: 3
    number-sections: false
  pdf:
    toc: true
    toc-depth: 3
    number-sections: false
    lof: true
    lot: true
  epub:
    toc: true
    toc-depth: 3
    number-sections: false
    lof: true
    lot: true
    mainfont: "Arial"
bibliography: ref.bib


