project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "assignment_gret1.qmd"
    - "assignment_r.qmd"
website:
  title: "OEKA201AssignmentMAT"
  navbar:
    left:
      - text: "Index"
        href: index.qmd
      - text: "Exercises using Gretl"
        href: assignment_gret1.pdf
      - text: "Exercises using R"
        href: assignment_r.pdf
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    mainfont: Monospace

  docx:
    toc: true
    toc-depth: 3

  pdf:
    toc: true
    toc-depth: 3
    number-sections: true

  epub:
    toc: true
    toc-depth: 3
    mainfont: Arial

bibliography: ref.bib



